// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef kashyyyk2_hpp
#define kashyyyk2_hpp
#include <FL/Fl.H>
#include "ui/yyy_chat_widget.hpp"
#include "ui/yyy_server_tree.hpp"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *user_list;
extern YYY::ServerTree *server_tree;
#include <FL/Fl_Pack.H>
extern YYY::ChatWidget *chat_widget;
#include <FL/Fl_Scrollbar.H>
extern Fl_Scrollbar *chat_scroll;
#include <FL/Fl_Group.H>
#include <FL/Fl_Return_Button.H>
#include <FL/Fl_Input.H>
extern Fl_Input *chat_box;
#include <FL/Fl_Menu_Bar.H>
Fl_Double_Window* YYY_MakeWindow();
extern Fl_Menu_Item menu_[];
#define join_menu_item (menu_+19)
#define disconnect_menu_item (menu_+20)
#define reconnect_menu_item (menu_+21)
#endif
