// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef yyy_connect_hpp
#define yyy_connect_hpp
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *recent_list;
#include <FL/Fl_Input.H>
#include <FL/Fl_Int_Input.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>
Fl_Double_Window* YYY_CreateConnectDialog();
#endif
