// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "kashyyyk2.hpp"
#include "yyy_callbacks.h"
#include "yyy_connect.hpp"

Fl_Browser *user_list=(Fl_Browser *)0;

YYY::ServerTree *server_tree=(YYY::ServerTree *)0;

YYY::ChatWidget *chat_widget=(YYY::ChatWidget *)0;

Fl_Scrollbar *chat_scroll=(Fl_Scrollbar *)0;

static void cb_(Fl_Return_Button*, void*) {
  YYY_Say(chat_box->value());
}

Fl_Input *chat_box=(Fl_Input *)0;

static void cb_Connect(Fl_Menu_*, void*) {
  static Fl_Window *const connect_dialog = YYY_CreateConnectDialog();
if(connect_dialog->shown()){
	const int x = connect_dialog->x(), y = connect_dialog->y();
	connect_dialog->hide();
	connect_dialog->show();
	connect_dialog->position(x, y);
}
else
	connect_dialog->show();
}

static void cb_Quit(Fl_Menu_*, void*) {
  exit(EXIT_SUCCESS);
}

static void cb_Say(Fl_Menu_*, void*) {
  YYY_Say(chat_box->value());
}

Fl_Menu_Item menu_[] = {
 {"File", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Connect...", FL_COMMAND|0x6b,  (Fl_Callback*)cb_Connect, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", FL_COMMAND|0x71,  (Fl_Callback*)cb_Quit, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Edit", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Cut", FL_COMMAND|0x78,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Copy", FL_COMMAND|0x63,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Paste", FL_COMMAND|0x76,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Select All", FL_COMMAND|0x61,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"View", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Zoom In", FL_COMMAND|0x3d,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Zoom Out", FL_COMMAND|0x2d,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Reset Zoom", FL_COMMAND|0x30,  0, 0, 128, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Light Theme", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Sunset Theme", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Dark Theme", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Server", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Join...", 0,  0, 0, 129, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Disconnect", FL_COMMAND|0x64,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Reconnect", FL_COMMAND|0x72,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Channel", 0,  0, 0, 64, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Say", 0,  (Fl_Callback*)cb_Say, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Leave", FL_COMMAND|0x77,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Rejoin", 0,  0, 0, 1, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Double_Window* YYY_MakeWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(630, 490, "Kashyyyk 2");
    w = o; if (w) {/* empty */}
    { Fl_Box* o = new Fl_Box(-5, 0, 640, 25);
      o->box(FL_THIN_UP_BOX);
      o->color(FL_LIGHT2);
    } // Fl_Box* o
    { Fl_Tile* o = new Fl_Tile(5, 24, 620, 432);
      o->labelfont(4);
      { Fl_Box* o = new Fl_Box(70, 48, 470, 381);
        Fl_Group::current()->resizable(o);
      } // Fl_Box* o
      { user_list = new Fl_Browser(505, 25, 120, 430);
        user_list->box(FL_THIN_DOWN_BOX);
        user_list->selection_color((Fl_Color)133);
        user_list->end();
      } // Fl_Browser* user_list
      { server_tree = new YYY::ServerTree(5, 25, 105, 430);
        server_tree->box(FL_THIN_DOWN_BOX);
        server_tree->color(FL_BACKGROUND2_COLOR);
        server_tree->selection_color((Fl_Color)133);
        server_tree->labeltype(FL_NORMAL_LABEL);
        server_tree->labelfont(0);
        server_tree->labelsize(14);
        server_tree->labelcolor(FL_FOREGROUND_COLOR);
        server_tree->align(Fl_Align(FL_ALIGN_TOP));
        server_tree->when(FL_WHEN_CHANGED);
        server_tree->end();
        server_tree->showroot(0);
      } // YYY::ServerTree* server_tree
      { Fl_Pack* o = new Fl_Pack(110, 24, 395, 432);
        o->type(1);
        { Fl_Box* o = new Fl_Box(110, 24, 5, 430);
          o->box(FL_THIN_DOWN_BOX);
        } // Fl_Box* o
        { chat_widget = new YYY::ChatWidget(115, 25, 370, 430);
          chat_widget->box(FL_THIN_DOWN_BOX);
          chat_widget->color(FL_BACKGROUND2_COLOR);
          chat_widget->selection_color((Fl_Color)133);
          chat_widget->labeltype(FL_NORMAL_LABEL);
          chat_widget->labelfont(0);
          chat_widget->labelsize(14);
          chat_widget->labelcolor(FL_FOREGROUND_COLOR);
          chat_widget->align(Fl_Align(FL_ALIGN_CENTER));
          chat_widget->when(FL_WHEN_RELEASE);
          Fl_Group::current()->resizable(chat_widget);
        } // YYY::ChatWidget* chat_widget
        { chat_scroll = new Fl_Scrollbar(485, 25, 15, 430);
          chat_scroll->selection_color(FL_LIGHT2);
        } // Fl_Scrollbar* chat_scroll
        { Fl_Box* o = new Fl_Box(500, 25, 5, 430);
          o->box(FL_THIN_DOWN_BOX);
        } // Fl_Box* o
        o->end();
      } // Fl_Pack* o
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Tile* o
    { Fl_Group* o = new Fl_Group(0, 455, 630, 35);
      o->box(FL_FLAT_BOX);
      o->color(FL_LIGHT2);
      { Fl_Return_Button* o = new Fl_Return_Button(595, 460, 30, 25);
        o->box(FL_THIN_UP_BOX);
        o->callback((Fl_Callback*)cb_);
      } // Fl_Return_Button* o
      { chat_box = new Fl_Input(5, 460, 585, 25);
        chat_box->box(FL_THIN_DOWN_BOX);
        chat_box->selection_color((Fl_Color)133);
        chat_box->textfont(4);
        Fl_Group::current()->resizable(chat_box);
      } // Fl_Input* chat_box
      o->end();
    } // Fl_Group* o
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 630, 25);
      o->box(FL_NO_BOX);
      o->color(FL_LIGHT2);
      o->selection_color((Fl_Color)21);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    o->size_range(480, 320);
    o->size_range(300, 200);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
